version: '3'

services:
  node_app:
    container_name: ContainerBackEND
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - ACCESS_TOKEN_SECRET=thisisjustarandomstringfortheaccesstokenbutnobodyisgonnagetit
      - REFRESH_TOKEN_SECRET=thisisjustarandomstringfortherefreshtokenbutnobodyisgonnagetit
      - MAILER_USER="moatazfoudhailii@gmail.com"
      - MAILER_PASS="kdel aiws mgsx mopc"
      - GOOGLE_CLIENT_ID=657623355311-49dhb3u2i6t8gi1t4ds82rco618roofa.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - DATABASE_URL="mongodb+srv://admin:lutadmin@lutcluster.hudxy73.mongodb.net/?retryWrites=true&w=majority"
      - CLIENT_URL="http://localhost:3001/payment"
